### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by jevgenijSy** [jjensn/home-assistant-grouped-lights#2]
Can you please write a readme what should be done to make this work in HA. Not everyone knows everything about integration. In my case I have an error: "Platform error light.grouped_light - Integration 'grouped_light' not found." and I dont know why.
1. Location of the py file: /config/custom_components/light/grouped_light.py
2. Restart the server.
3. Configuration.yaml: 
```
light:
  - platform: grouped_light
    name: Strips
    entities:
      - light.strip1
      - light.strip2
```
4. Restart the server. -> error

If this steps are invalid, please write a detailed readme so people can integrate this feature 👍 thanks
